// Vercel-safe, bundled search ontology for paper-search query intent.
//
// This file intentionally contains only public/generic vocabulary: journal/source
// names, source-title fragments, and biomedical method/topic terms.  Private
// runtime artifacts (full SHawn corpus DB, licensed JCR indexes, credentials,
// large caches) must stay outside git.  Regenerate/extend this file locally via
// `pnpm run search:build-ontology -- --write-js` after curator review.

export const SEARCH_ONTOLOGY_VERSION = '2026-05-08.p0-vercel-ontology';

export const SEARCH_ONTOLOGY_VENUES = [
  'nature',
  'nature communications',
  'nature medicine',
  'nature genetics',
  'nature biotechnology',
  'nature cell biology',
  'nature methods',
  'science',
  'science advances',
  'cell',
  'cell stem cell',
  'cell reports',
  'cell reports medicine',
  'developmental cell',
  'current biology',
  'elife',
  'plos one',
  'plos biology',
  'pnas',
  'proceedings of the national academy of sciences',
  'world journal of surgical oncology',
  'clinical science',
  'annual review',
  'annual reviews',
  'biology of reproduction',
  'reproductive biology and endocrinology',
  'immunological reviews',
  'international journal of molecular sciences',
  'frontiers in endocrinology',
  'scientific reports',
  'biorxiv',
  'bio rxiv',
  'medrxiv',
  'med rxiv',
];

export const SEARCH_ONTOLOGY_VENUE_FRAGMENTS = [
  'journal', 'journals', 'reports', 'reviews', 'review', 'frontiers', 'proceedings',
  'letters', 'communications', 'transactions', 'annals', 'annual', 'archives', 'bulletin',
  'biology', 'reproductive', 'reproduction', 'endocrinology', 'oncology', 'medicine', 'sciences',
  'molecular', 'surgical', 'immunological', 'scientific', 'international', 'clinical', 'science', 'world',
];

export const SEARCH_ONTOLOGY_VENUE_TERMINALS = [
  'journal', 'journals', 'reports', 'reviews', 'letters', 'communications',
  'proceedings', 'biology', 'reproduction', 'endocrinology', 'oncology',
  'medicine', 'sciences', 'cell',
];

export const SEARCH_ONTOLOGY_BIO_TERMS = [
  'endometrium', 'endometrial', 'uterus', 'uterine', 'organoid', 'organoids',
  'transcriptomics', 'transcriptome', 'transcriptional', 'transcription',
  'genomics', 'genomic', 'genome', 'proteomics', 'proteomic',
  'metabolomics', 'metabolomic', 'lipidomics',
  'decidua', 'decidual', 'decidualization',
  'implantation', 'receptivity', 'fertility', 'infertility',
  'estrogen', 'estradiol', 'progesterone', 'testosterone', 'melatonin',
  'cholesterol', 'steroid', 'androgen', 'pten', 'akt', 'foxo3a',
  'carcinoma', 'cancer', 'tumor', 'tumour', 'fibroid', 'leiomyoma',
  'pancreatic', 'breast', 'bladder', 'colorectal', 'gastric', 'lung', 'liver',
  'endometriosis', 'adenomyosis',
  'stem', 'cell', 'cells', 'expression', 'gene', 'genes',
  'protein', 'proteins', 'rna', 'dna', 'mrna', 'cdna',
  'chromatin', 'histone', 'epigenetic', 'epigenetics',
  'mouse', 'human', 'bovine', 'equine', 'porcine', 'canine', 'murine',
  'mice', 'rat', 'rats', 'pig', 'pigs', 'swine', 'sus', 'scrofa', 'zebrafish',
  'analysis', 'profiling', 'sequencing', 'pathway', 'pathways',
  'cluster', 'clustering', 'network', 'regulation', 'signaling',
  'methylation', 'acetylation', 'phosphorylation', 'ubiquitination',
  'proliferation', 'apoptosis', 'differentiation', 'migration',
  'invasion', 'adhesion', 'inflammation', 'immune', 'cytokine',
  'hormone', 'receptor', 'enzyme', 'kinase', 'phosphatase',
  'embryo', 'blastocyst', 'trophoblast', 'placenta', 'menstrual',
  'ovary', 'ovarian', 'cervical', 'cervix', 'fallopian', 'vaginal',
  'single', 'spatial', 'bulk', 'scrna', 'scrnaseq',
  'organotypic', 'culture', 'tissue', 'sample', 'patient', 'patients',
  'clinical', 'vitro', 'vivo', 'study', 'studies', 'review', 'reviews', 'model',
  'therapy', 'treatment', 'surgery', 'diagnosis',
  'biomarker', 'biomarkers', 'diagnostic', 'prognostic',
  'rnaseq', 'atacseq', 'chipseq', 'bisulfite',
  'data', 'dataset', 'database',
  'serum', 'elisa', 'leukocyte', 'leukocytes', 'tryptophan', 'dioxygenase',
  'alternative', 'critical', 'current', 'knowledge', 'identification', 'major',
  'decoding', 'understanding', 'mysterious', 'changes', 'change', 'niche',
  'limitations', 'limitation', 'animal', 'animals', 'predicting', 'myomatous',
  'erythrocytosis', 'wound', 'healing', 'mesenchymal', 'platelet', 'platelets',
  'infusion', 'bone', 'modeling', 'modelling', 'early', 'stages', 'stage', 'science',
  'influence', 'factors', 'effectiveness', 'casein', 'agonist', 'toxicological',
  'pathology', 'stimulated', 'histological', 'staining', 'functional', 'analyses',
  'collagen', 'deposition', 'evaluation', 'epithelial', 'annual',
  'steroidogenic', 'self', 'selfpatterning', 'postimplantation', 'development', 'schwann',
  'mechanism', 'lipopolysaccharide', 'secretion', 'enhanced', 'improvement',
  'elafin', 'antiprotease', 'sialic', 'acid', 'personalized', 'computational',
  'natural', 'killer', 'pregnancy',
  'macrophage', 'macrophages', 'quantitative', 'real', 'time', 'pcr', 'situ',
  'hybridization', 'immunohistochemistry', 'western', 'blot', 'immunofluorescence',
  'proteinuria', 'bun', 'histology', 'glomeruli', 'control', 'secretory',
  'infertile', 'reports', 'journal', 'journals', 'frontiers', 'proceedings',
  'communications', 'biology', 'reproductive', 'reproduction', 'endocrinology', 'oncology', 'sciences',
  'pcos', 'syndrome', 'disorder', 'disease', 'fibrosis', 'granulosa', 'follicle',
  'follicular', 'luteal', 'corpus', 'polycystic', 'conceptus', 'trophectoderm',
  'interferon', 'interleukin', 'cytokines',
];
